
package ws.core.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculator", targetNamespace = "http://ws.core/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://ws.core/", className = "ws.core.client.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ws.core/", className = "ws.core.client.AddResponse")
    @Action(input = "http://ws.core/Calculator/addRequest", output = "http://ws.core/Calculator/addResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mul", targetNamespace = "http://ws.core/", className = "ws.core.client.Mul")
    @ResponseWrapper(localName = "mulResponse", targetNamespace = "http://ws.core/", className = "ws.core.client.MulResponse")
    @Action(input = "http://ws.core/Calculator/mulRequest", output = "http://ws.core/Calculator/mulResponse")
    public int mul(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sub", targetNamespace = "http://ws.core/", className = "ws.core.client.Sub")
    @ResponseWrapper(localName = "subResponse", targetNamespace = "http://ws.core/", className = "ws.core.client.SubResponse")
    @Action(input = "http://ws.core/Calculator/subRequest", output = "http://ws.core/Calculator/subResponse")
    public int sub(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "greet", targetNamespace = "http://ws.core/", className = "ws.core.client.Greet")
    @ResponseWrapper(localName = "greetResponse", targetNamespace = "http://ws.core/", className = "ws.core.client.GreetResponse")
    @Action(input = "http://ws.core/Calculator/greetRequest", output = "http://ws.core/Calculator/greetResponse")
    public String greet(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "div", targetNamespace = "http://ws.core/", className = "ws.core.client.Div")
    @ResponseWrapper(localName = "divResponse", targetNamespace = "http://ws.core/", className = "ws.core.client.DivResponse")
    @Action(input = "http://ws.core/Calculator/divRequest", output = "http://ws.core/Calculator/divResponse")
    public int div(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
